### ISSUE TITLE
How add other AI?

### ISSUE THREAD

**Issue by Tomirad** [icebaker/sublime-nano-bots#5]
Please add more information to the description about adding additional AI. Where should the .yml file be etc.

Example catridge - 

```
---
meta:
  symbol: 🦙
  name: Llama3.2
  author: Ollama.com
  version: 0.4.2
  license: CC0-1.0
  description: https://github.com/ollama/oll; ollama run

behaviors:
  interaction:
    directive: You are a helpful assistant.
    
provider:
  id: ollama
  credentials:
    address: 127.0.0.1:11434
  settings:
    model: llama3.2
    format: json
    raw: false
    options:
      num_keep: 5
      seed: 42
      num_predict: 100
      top_k: 20
      top_p: 0.9
      tfs_z: 0.5
      typical_p: 0.7
      repeat_last_n: 33
      temperature: 0.8
      repeat_penalty: 1.2
      presence_penalty: 1.5
      frequency_penalty: 1.0
      mirostat: 1
      mirostat_tau: 0.8
      mirostat_eta: 0.6
      penalize_newline: true
      numa: false
      num_ctx: 1024
      num_batch: 2
      num_gpu: 1
      main_gpu: 0
      low_vram: false
      f16_kv: true
      vocab_only: false
      use_mmap: true
      use_mlock: false
      num_thread: 8
      stop: 
        - "\n"
        - "user:"
```

More... my Preferences.sublime-settings

```
{
	"ignored_packages":
	[
		"Vintage",
	],
	"color_scheme": "Mariana.sublime-color-scheme",
	"theme": "Monokai Pro.sublime-theme",
	"font_size": 15,
	"index_files": true,
	"font_face": "Cascadia Code Light",
	"dark_theme": "Adaptive.sublime-theme",
	"light_theme": "Adaptive.sublime-theme",
	"close_windows_when_empty": false,
	"NANO_BOTS_API_ADDRESS": "//127.0.0.1:11434",
	"NANO_BOTS_STREAM": true,
	"NANO_BOTS_END_USER": "anonymous"
}
```
After used I have errors in Sublime Text console:
```
Rreloading settings Packages/User/Preferences.sublime-settings
Exception in thread Thread-222:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File ".\AppData\Roaming\Sublime Text\Installed Packages\Nano Bots.sublime-package\nanobot_helpers.py", line 50, in fetch
    if cartridge['meta']['symbol']:
TypeError: string indices must be integers

```
